INSERT INTO genre (description,name)
VALUES  ('Popular music at the time of producing the track. This is generally commercialized music.','Pop'),
        ('Percussive electronic music made for nightclubs, raves and festivals.','Dance/Electronic'),
        ('When the lyrics are spoken rather(rather than sung) in a rapid, rhythmic way.','Rap'),
        ('A less intense version of rock and a more intense version of pop. Loose fit music falls here.','Alternative/Indie');

INSERT INTO artist (name)
VALUES  ('Adele'),
        ('Gorillaz'),
        ('Childish Gambino'),
        ('Daft Punk');

INSERT INTO user (username,password)
VALUES  ('test','$2a$10$U7fFuQzETf8RxNgoYuHqQ.j5eybKjBc0.Fxo8DK3UwnfkGdYFk4qy'),
        ('alice','$2a$10$OrFa3yYtEAzi7eduZmdmt.6uT67t/6HpRb640bF150g51w8OKM0Qa'),
        ('dog','$2a$10$7aYV7xZrlbHt0L.w4qnnduBhYviB6it69lxUV6aTQtlOY4NeDvz.2');

INSERT INTO user (username,password, permissions)
VALUES  ('admin','$2a$10$U7fFuQzETf8RxNgoYuHqQ.j5eybKjBc0.Fxo8DK3UwnfkGdYFk4qy',1);

INSERT INTO album (name,artist_id,genre_id, cover)
VALUES  ('21',1,1,'https://upload.wikimedia.org/wikipedia/en/1/1b/Adele_-_21.png'),
        ('Because the Internet',3,3,'https://i.pinimg.com/originals/b9/a1/b7/b9a1b7038d5b9f890e9a6cafbada52ca.jpg'),
        ('Discovery',4,2,'https://weraveyou.com/wp-content/uploads/2016/02/71bsHTr6idL._SL1500_.jpg'),
        ('Demon Days',2,4,'https://images-na.ssl-images-amazon.com/images/I/71lix6%2BVfWL._AC_SX522_.jpg'),
        ('Song Machine',2,4, 'https://alextimes.com/wp-content/uploads/2020/11/TL-AlbumCover.jpg');

INSERT INTO playlist (artwork,description,name,user_id)
VALUES  ('https://petapixel.com/assets/uploads/2016/09/saladwoman-744x700.jpg','Simple playlist when I dunno what to listen to.','Another Day, Another Generic Playlist',1),
        ('https://www.greenenergynews.co.uk/wp-content/uploads/2019/10/sun-free-use-generic-stock.jpg','For a strong start to a good day.','Bright Day',1),
        ('https://previews.123rf.com/images/dny3d/dny3d1009/dny3d100900014/7742170-3d-man-with-plugs-and-cables-generic.jpg','When the party is dead and you wanna fill the room with more energy!','Cut the Tension',1),
        ('https://www.adobe.com/content/dam/cc/us/en/products/creativecloud/stock/stock-riverflow1-720x522.jpg.img.jpg','Dance Dance Dance!','Dance!',2),
        ('https://images.cnbctv18.com/wp-content/uploads/2019/05/market-bse-nse-AP19140389295321-768x524.jpg','Beats so sick, you would think they were made by aliens!','Extraterrestrial Beats',3);

INSERT INTO track (duration,lyrics,name,album_id)
VALUES  (228,'Lorem Ipsum is simply dummy text of the printing and','Rolling in the Deep',1),
        (250,'Lorem Ipsum is simply dummy text of the printing and','Turning Tables',1),
        (243,'Lorem Ipsum is simply dummy text of the printing and','Don''t you remember',1),
        (243,'Lorem Ipsum is simply dummy text of the printing and','Set Fire to the Rain',1),
        (278,'Lorem Ipsum is simply dummy text of the printing and','He Won''t Go',1),
        (228,'Lorem Ipsum is simply dummy text of the printing and','Take It All',1),
        (241,'Lorem Ipsum is simply dummy text of the printing and','I''ll Be Waiting',1),
        (348,'Lorem Ipsum is simply dummy text of the printing and','One and Only',1),
        (316,'Lorem Ipsum is simply dummy text of the printing and','Lovesong',1),
        (285,'Lorem Ipsum is simply dummy text of the printing and','Someone Like You',1),
        (4,'Lorem Ipsum is simply dummy text of the printing and','The Library (Intro)',2),
        (209,'Lorem Ipsum is simply dummy text of the printing and','I. Crawl',2),
        (244,'Lorem Ipsum is simply dummy text of the printing and','II. Worldstar',2),
        (44,'Lorem Ipsum is simply dummy text of the printing and','Dial Up',2),
        (219,'Lorem Ipsum is simply dummy text of the printing and','I. The Worst Guys',2),
        (231,'Lorem Ipsum is simply dummy text of the printing and','II. Shadows',2),
        (210,'Lorem Ipsum is simply dummy text of the printing and','III. Telegraph Ave. ("Oakland" by Lloyd)',2),
        (180,'Lorem Ipsum is simply dummy text of the printing and','IV. Sweatpants',2),
        (234,'Lorem Ipsum is simply dummy text of the printing and','V. 3005',2),
        (54,'Lorem Ipsum is simply dummy text of the printing and','Playing Around Before the Party Starts',2),
        (91,'Lorem Ipsum is simply dummy text of the printing and','I. The Party',2),
        (171,'Lorem Ipsum is simply dummy text of the printing and','II. No Exit',2),
        (43,'Lorem Ipsum is simply dummy text of the printing and','Death by Numbers',2),
        (344,'Lorem Ipsum is simply dummy text of the printing and','I. Flight of the Navigator',2),
        (290,'Lorem Ipsum is simply dummy text of the printing and','II. Zealots of Stockholm (Free Information)',2),
        (73,'Lorem Ipsum is simply dummy text of the printing and','III. Urn',2),
        (207,'Lorem Ipsum is simply dummy text of the printing and','I. Pink Toes',2),
        (282,'Lorem Ipsum is simply dummy text of the printing and','II. Earth: The Oldest Computer (The Last Night)',2),
        (342,'Lorem Ipsum is simply dummy text of the printing and','III. Life: The Biggest Troll (Andrew Auernheimer)',2),
        (320,'Lorem Ipsum is simply dummy text of the printing and','One More Time',3),
        (207,'Lorem Ipsum is simply dummy text of the printing and','Aerodynamic',3),
        (298,'Lorem Ipsum is simply dummy text of the printing and','Digital Love',3),
        (225,'Lorem Ipsum is simply dummy text of the printing and','Harder, Better, Faster, Stronger',3),
        (211,'Lorem Ipsum is simply dummy text of the printing and','Crescendolls',3),
        (104,'Lorem Ipsum is simply dummy text of the printing and','Nightvision',3),
        (237,'Lorem Ipsum is simply dummy text of the printing and','Superheroes',3),
        (202,'Lorem Ipsum is simply dummy text of the printing and','High Life',3),
        (231,'Lorem Ipsum is simply dummy text of the printing and','Something About us',3),
        (224,'Lorem Ipsum is simply dummy text of the printing and','Voyager',3),
        (344,'Lorem Ipsum is simply dummy text of the printing and','Veridis Quo',3),
        (206,'Lorem Ipsum is simply dummy text of the printing and','Short Circuit',3),
        (238,'Lorem Ipsum is simply dummy text of the printing and','Face to Face',3),
        (600,'Lorem Ipsum is simply dummy text of the printing and','Too Long',3),
        (67,'Lorem Ipsum is simply dummy text of the printing and','Intro',4),
        (195,'Lorem Ipsum is simply dummy text of the printing and','Last Living Souls',4),
        (225,'Lorem Ipsum is simply dummy text of the printing and','Kids with Guns',4),
        (285,'Lorem Ipsum is simply dummy text of the printing and','O Green World',4),
        (230,'Lorem Ipsum is simply dummy text of the printing and','Dirt Harry',4),
        (222,'Lorem Ipsum is simply dummy text of the printing and','Feel Good Inc',4),
        (230,'Lorem Ipsum is simply dummy text of the printing and','El Manana',4),
        (295,'Lorem Ipsum is simply dummy text of the printing and','Every Planet We Reach Is Dead',4),
        (165,'Lorem Ipsum is simply dummy text of the printing and','November Has Come',4),
        (213,'Lorem Ipsum is simply dummy text of the printing and','All Alone',4),
        (133,'Lorem Ipsum is simply dummy text of the printing and','White Ligh',4),
        (245,'Lorem Ipsum is simply dummy text of the printing and','Dare',4),
        (199,'Lorem Ipsum is simply dummy text of the printing and','Fire Coming out of the Monkey''s Head',4),
        (231,'Lorem Ipsum is simply dummy text of the printing and','Don''t Get Lost in Heaven',4),
        (268,'Lorem Ipsum is simply dummy text of the printing and','Demon Days',4),
        (228,'Lorem Ipsum is simply dummy text of the printing and','Strange Timez',5),
        (181,'Lorem Ipsum is simply dummy text of the printing and','The Valley of The Pagans',5),
        (244,'Lorem Ipsum is simply dummy text of the printing and','The Lost Chord',5),
        (193,'Lorem Ipsum is simply dummy text of the printing and','Pac-Man',5),
        (183,'Lorem Ipsum is simply dummy text of the printing and','Chalk Tablet Towers',5),
        (253,'Lorem Ipsum is simply dummy text of the printing and','The Pink Phantom',5),
        (253,'Lorem Ipsum is simply dummy text of the printing and','Aries',5),
        (215,'Lorem Ipsum is simply dummy text of the printing and','Friday 13th',5),
        (274,'Lorem Ipsum is simply dummy text of the printing and','Dead Butterflies',5),
        (333,'Lorem Ipsum is simply dummy text of the printing and','Desole',5),
        (221,'Lorem Ipsum is simply dummy text of the printing and','Momentary Bliss',5),
        (411,'Lorem Ipsum is simply dummy text of the printing and','Opium',5),
        (164,'Lorem Ipsum is simply dummy text of the printing and','Simplicity',5),
        (214,'Lorem Ipsum is simply dummy text of the printing and','Severed Head',5),
        (181,'Lorem Ipsum is simply dummy text of the printing and','With Love To An Ex',5),
        (193,'Lorem Ipsum is simply dummy text of the printing and','MLS',5),
        (164,'Lorem Ipsum is simply dummy text of the printing and','How Far?',5);

INSERT INTO track_playlist (playlists_id,tracks_id)
VALUES  (1,1),
        (1,3),
        (1,18),
        (1,53),
        (1,6),
        (1,27),
        (1,45),
        (1,72),
        (2,37),
        (2,2),
        (2,14),
        (2,5),
        (2,37),
        (2,28),
        (2,62),
        (2,46),
        (2,68),
        (2,47),
        (3,12),
        (3,4),
        (3,62),
        (3,40),
        (3,65),
        (3,54),
        (3,61),
        (3,25),
        (4,4),
        (4,52),
        (4,69),
        (4,51),
        (4,58),
        (4,26),
        (4,40),
        (5,17),
        (5,46),
        (5,42),
        (5,32),
        (5,68),
        (5,59),
        (5,47),
        (5,19),
        (5,64),
        (5,10),
        (5,9),
        (5,15),
        (5,54),
        (5,13),
        (5,34);


